export const US_REGIONS = {
  NORTHEAST: 'Northeast',
  MIDWEST: 'Midwest',
  SOUTH: 'South',
  WEST: 'West',
} as const;

export type UsRegion = (typeof US_REGIONS)[keyof typeof US_REGIONS];

export const STATE_REGION_MAP: Record<string, UsRegion> = {
  AL: 'South',
  AK: 'West',
  AZ: 'West',
  AR: 'South',
  CA: 'West',
  CO: 'West',
  CT: 'Northeast',
  DE: 'South',
  FL: 'South',
  GA: 'South',
  HI: 'West',
  ID: 'West',
  IL: 'Midwest',
  IN: 'Midwest',
  IA: 'Midwest',
  KS: 'Midwest',
  KY: 'South',
  LA: 'South',
  ME: 'Northeast',
  MD: 'South',
  MA: 'Northeast',
  MI: 'Midwest',
  MN: 'Midwest',
  MS: 'South',
  MO: 'Midwest',
  MT: 'West',
  NE: 'Midwest',
  NV: 'West',
  NH: 'Northeast',
  NJ: 'Northeast',
  NM: 'West',
  NY: 'Northeast',
  NC: 'South',
  ND: 'Midwest',
  OH: 'Midwest',
  OK: 'South',
  OR: 'West',
  PA: 'Northeast',
  RI: 'Northeast',
  SC: 'South',
  SD: 'Midwest',
  TN: 'South',
  TX: 'South',
  UT: 'West',
  VT: 'Northeast',
  VA: 'South',
  WA: 'West',
  WV: 'South',
  WI: 'Midwest',
  WY: 'West',
  DC: 'South',
};

export const STATE_NAMES: Record<string, string> = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
  DC: 'District of Columbia',
};
